### ISSUE TITLE
Ability to blacklist app update in the updates window

### ISSUE THREAD

**Issue by bocekm** [TheAurora/Aurora-Store#4]
Please add a way to prevent an app from updating in the window for updates. For example in a menu triggered by long tap.
First I thought the app does not allow that but then I managed to get to Settings (https://github.com/TheAurora/Aurora-Store/issues/3) and found out it's possible to blacklist them there. But I guess not everybody would find it there.

**Comment by whyorean** [comment]
You just swipe Right to Left on updatable apps list to black list them

**Comment by bocekm** [comment]
Thanks, I wasn't aware of that feature.
